[project]
name = "brain-image-implementation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dreamsim",
    "torch",
    "torchvision",
    "torchsummary",
    "tensorboard",
    "torch_geometric",
    "lightning",
    "triton",

    "numpy",
    "einops",
    "pandas",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "Pillow",
    "jupyter",
    "ipykernel",

    "tqdm",
    "pydantic",
    "hydra-core",
    "omegaconf",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src"]