#align_target_encoder: "unaligned_synclr_vitb16"
align_img_encoder: "clip_vith14"
recon_latent_encoder: "sd_variations_v2"
prior_img_encoder: "clip_vith14"
#eeg_encoder: "nice"
eeg_encoder: "atms"

do_align: true
do_recon: false
do_recon_low: false

debug_prior_use_target_as_cond: false
debug_metrics: false
log_gradients: false
plot_lowdim_proj: true
low_dim_proj_pca: 50

align_loss_type: clip

skip_eval_first_epoch: true
full_eval_every_epochs: 5

prior: 
  norm_scheme: null

encoder_lr: 3e-4
encoder_min_lr: 1e-6
encoder_warmup_epochs: 1
encoder_delay_epochs: 0

prior_lr: 1e-3
prior_min_lr: 1e-6
prior_warmup_epochs: 5
prior_delay_epochs: 0

lr_scheduler: "cosine_anneal"
betas: [0.9, 0.999]

max_epochs: 30

temperature_init: 0.07