# EEG Dataset Configuration

# Data paths
data_path: data/things-eeg2
imgs_dir: imgs
eeg_dir: eeg
latents_dir: img-latents

# Dataset parameters
train_imgs_per_concept: 10
test_imgs_per_concept: 1
subs: [1,2,3,4,5,6,7,8,9,10]

# DataLoader parameters
batch_size: 32
val_batch_size: 32
eval_batch_size: 32
shuffle_train: true
limit_train_size: 1.0
limit_val_size: 1.0
limit_test_size: 1.0
num_workers: 8 