defaults:
  - data_config
  - _self_

batch_size: 256
models:
  - synclr
  - aligned_synclr
splits:
  - train
  - test
img_size: [224, 224]
models_path: models
dtype: float32
device: cuda
output_dir: null