defaults:
  - base
  - dataset: things-eeg2
  - _self_

model_names:
  - t5_base

splits:
  - train
  - test

stat_path: statistics/qwen3.5-0.8b
cache_dir: tensorcache/qwen3.5-0.8b
batch_size: 512

dataset:
  subs: [1]
