defaults:
  - base
  - dataset: things-eeg2
  - _self_

model_names:
- aligned_synclr_vitb16
- unaligned_synclr_vitb16
- clip_vith14  
- clip_vitl14

splits:
  - train
  - test

models_path: models
dtype: float32
device: null
download_weights: true
cache_dir: tensorcache
compile: true
