defaults:
  - base
  - dataset: things-eeg2
  - _self_

model_names:
  - t5_base

caption_path: data/things-eeg2/captions/qwen3.5-0.8b.jsonl

splits:
  - train
  - test

batch_size: 256
dtype: float32
device: null
compile: false
cache_dir: tensorcache/qwen3.5-0.8b

dataset:
  subs: [1]
