# Embedding generation configuration

# Default components
defaults:
  - _self_

model_names: aligned_synclr_vitb16  

# Generation settings
batch_size: 128
splits:
  - train
  - test

models_path: models
dtype: float32
device: null
download_weights: true
output_dir: tensorcache
img_dir: data/things-eeg2/imgs
compile: true