# NICE Model Configuration
model_name: aligned_synclr
project_dim: 256
img_latent_dim: 768

# Learning rate settings
encoder_lr: 8e-3
projector_lr: 8e-3
lr_scheduler: cosine_anneal
betas: [0.9, 0.999]
encoder_min_lr: 1e-4
projector_min_lr: 1e-4

# Training schedule
projector_warmup_epochs: 2
encoder_warmup_epochs: 4
warmup_start_frac: 0.1
max_epochs: 100
num_workers: 8

# Model parameters
temperature_init: 2.659260  # log(1/0.07)
data_seed: 42

# EEG Encoder Configuration (can be overridden)
eeg_config:
  embed_dim: 40
  encoded_dim: 1440
  proj_dim: 768
  temporal_kernel_size: 25
  spatial_kernel_size: 17
  temporal_pool_size: 41
  temporal_stride: 1
  hidden_dim: 40
  dropout: 0.5 