# Sweep Configuration for NICE Model Training

# Default components for sweep training
defaults:
  - dataset: eeg_dataset_fast
  - model: nice_model
  - trainer: nice_trainer_sweep
  - encoder: eeg_encoder
  - _self_

# Script-specific settings
script_name: sweep
description: "Parameter sweep for NICE model training"

# Sweep configuration
sweep:
  # Sweep type: random, grid, bayes, lr, architecture
  type: bayes
  
  # Number of runs to execute
  count: 100
  
  # Wandb settings
  project: brain-image-nice
  entity: null  # Set to your wandb username or team name
  
  # Metric to optimize
  metric:
    name: top1_acc
    goal: maximize
  
  # Early termination
  early_terminate:
    type: hyperband
    min_iter: 5
  
  # Parameter configurations for different sweep types
  parameters:
    random:
      model.encoder_lr:
        min: 1e-4
        max: 1e-2
        distribution: log_uniform
      model.projector_lr:
        min: 1e-4
        max: 1e-2
        distribution: log_uniform
      model.project_dim:
        values: [128, 256, 512]
    
    grid:
      model.encoder_lr:
        values: [1e-3, 5e-3, 8e-3, 5e-4]
      model.projector_lr:
        values: [1e-3, 5e-3, 8e-3, 1e-2]
    
    bayes:
      model.encoder_lr:
        min: 1e-4
        max: 1e-2
        distribution: log_uniform
      model.projector_lr:
        min: 1e-4
        max: 1e-2
        distribution: log_uniform
      model.project_dim:
        values: [128, 256, 512]
      encoder.hidden_dim:
        values: [10, 20, 40, 80]
      encoder.temporal_kernel_size:
        values: [20, 40, 80]
      encoder.spatial_kernel_size:
        values: [20, 40, 80]
      encoder.final_temporal_size:
        values: [2, 4, 6]
      encoder.final_spatial_size:
        values: [2, 4, 6]
    
    lr:
      model.encoder_lr:
        values: [1e-4, 5e-4, 1e-3, 5e-3, 8e-3, 1e-2, 2e-2]
      model.projector_lr:
        values: [1e-4, 5e-4, 1e-3, 5e-3, 8e-3, 1e-2, 2e-2]
      model.encoder_min_lr:
        values: [1e-5, 1e-4, 5e-4]
      model.projector_min_lr:
        values: [1e-5, 1e-4, 5e-4]
    
    architecture:
      model.project_dim:
        values: [128, 256, 512, 1024]
      model.img_latent_dim:
        values: [512, 768, 1024]
      encoder.hidden_dim:
        values: [10, 20, 40, 80, 160]
      encoder.temporal_kernel_size:
        values: [10, 20, 40, 80, 160]
      encoder.spatial_kernel_size:
        values: [10, 20, 40, 80, 160]
      encoder.final_temporal_size:
        values: [2, 3, 4, 5, 6]
      encoder.final_spatial_size:
        values: [2, 3, 4, 5, 6]