# Training configuration for NICE model

# Default components for NICE training
defaults:
  - dataset: eeg_dataset
  - model: nice_model
  - trainer: nice_trainer
  - encoder: eeg_encoder
  - _self_

# Script-specific settings
script_name: train_nice
description: "Training script for NICE model with EEG data"

# Global overrides for this script
device: cuda
precision: 16
num_workers: 4
compile_model: true
log_path: logs
checkpoint_path: null
