defaults:
  - train_eeg
  - _self_

model:
  do_align: true
  do_recon: false
  do_recon_low: false

  encoder_lr: 3e-4
  encoder_min_lr: 1e-5
  encoder_warmup_epochs: 1

  align_img_encoder: "aligned_synclr_vitb16"


  modules_to_train:
    - eeg_encoder

  max_epochs: 40
  full_eval_every_epochs: 10

trainer:
  checkpoint_monitor_early_stop: 10
  check_val_every_n_epochs: 5

dataset:
  batch_size: 512
  val_batch_size: 256
  test_batch_size: 256