defaults:
  - train_eeg
  - _self_

model:
  do_align: true
  do_recon: true
  do_recon_low: false
  
  eeg_encoder_path: null
  #eeg_encoder_path: checkpoints/align-atms-clip_vith14-local-train/train_eeg-epoch_37-val-loss_0.2236.ckpt

  encoder_lr: 1e-3
  encoder_min_lr: 1e-7
  encoder_warmup_epochs: 5
  encoder_delay_epochs: 0

  modules_to_train:
    - eeg_encoder
    - prior

  #encoder_delay_epochs: 0
  #encoder_lr: 3e-4
  #encoder_min_lr: 1e-7

  prior_lr: 1e-3
  prior_min_lr: 1e-7
  prior_warmup_epochs: 5
  prior_delay_epochs: 10

  max_epochs: 500
  #max_epochs: 150

trainer:
  checkpoint_monitor_early_stop: 150

dataset:
  batch_size: 512
  val_batch_size: 256
  test_batch_size: 256