defaults:
  - base
  - dataset: things-eeg2
  - model: comm_model
  - trainer: comm_trainer
  - _self_

checkpoint_path: null
resume_training: false

model:
  seed: 42
  max_epochs: 30
  embed_dim: 512
  proj_dim: 256

dataset:
  batch_size: 64