defaults:
  - train_eeg
  - override augmentation: none
  - _self_

model:
  do_align: true
  do_recon: false
  do_recon_low: false
  aug_eeg: false
  align_loss_type: infonce
  align_loss_factor: 1.0
  align_mse_loss_factor: 0.0

  encoder_lr: 3e-4
  encoder_min_lr: 1e-5
  encoder_warmup_epochs: 1

  align_img_encoder: "t5_base"

  modules_to_train:
    - eeg_encoder

  max_epochs: 200
  full_eval_every_epochs: 20

trainer:
  checkpoint_monitor: "val/align/top1"
  checkpoint_monitor_mode: "max"
  checkpoint_monitor_early_stop: 20
  check_val_every_n_epochs: 5
  cache_dir: tensorcache/qwen3.5-0.8b

dataset:
  batch_size: 32
  val_batch_size: 32
  test_batch_size: 32
  num_workers: 4
  stats_path: statistics/qwen3.5-0.8b
