defaults:
  - train_low_level
  - _self_

model:
  max_epochs: 100
  use_perceptual_loss: true
  perceptual_loss_model: "unaligned_synclr_vitb16"
  eval_batch_size: 16

dataset:
  batch_size: 16
  val_batch_size: 16
  test_batch_size: 16
