defaults:
  - base
  - dataset: eeg_dataset
  - model: eeg_model
  - trainer: eeg_trainer
  - _self_

checkpoint_path: null
resume_training: false

model:
  plot_lowdim_proj: false
  low_dim_proj_pca: 50