hydra:
  run:
    dir: .
  output_subdir: null

defaults:
  - dataset: eeg_dataset
  - model: eeg_model
  - trainer: eeg_trainer
  - wandb: wandb
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

checkpoint_path: null
resume_training: false