defaults:
  - train_eeg
  - _self_

model:
  do_align: false
  do_recon: true
  do_recon_low: false
  
  eeg_encoder_path: null

  encoder_lr: 1e-3
  encoder_min_lr: 1e-7
  encoder_warmup_epochs: 5
  encoder_delay_epochs: 0

  align_img_encoder: "aligned_synclr_vitb16"

  modules_to_train:
    - eeg_encoder
    - prior

  prior_lr: 1e-3
  prior_min_lr: 1e-7
  prior_warmup_epochs: 5
  prior_delay_epochs: 0

  max_epochs: 500
  #max_epochs: 150

  full_eval_every_epochs: 20

trainer:
  checkpoint_monitor_early_stop: 150
  check_val_every_n_epochs: 5

dataset:
  batch_size: 1024
  val_batch_size: 256
  test_batch_size: 256