# NICE Trainer Configuration

# Training settings
run_name: nice
num_epochs: 100
num_workers: 32

# Model compilation and initialization
compile_model: true
init_weights: true

# Logging and checkpointing
log_dir: logs
checkpoint_dir: null
enable_barebones: false
overfit_batches: 0
precision: 16
val_check_interval: 1.0
log_every_n_steps: 100
enable_progress_bar: true
enable_model_summary: true
save_checkpoints: false
save_top_k: 0

# Wandb settings
enable_wandb: true
wandb_project: brain-image-nice
wandb_entity: null  # Set to your wandb username or team name
wandb_log_model: false
wandb_tags: [sweep]

# Device settings
device: cuda
accelerator: auto 