# EEG Encoder Configuration

# Convolutional parameters
temporal_kernel_size: 25
spatial_kernel_size: 17
temporal_pool_size: 41
temporal_stride: 1
hidden_dim: 40
dropout: 0.5 

# Final dimensions
final_spatiotemporal_size: 36